### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by SimonSchama** [b0npls/ErikIsAGoodTutorial#2]
I have pushed a new branch 'erik' to GitHub. On this branch I have created a Tree of Life spritesheet, some animations, and a game object that hooks them up to controller input. As I have never worked in Unity before I would like our resident unity expert b0n to make sure everything is good/educate me on design and development workflows before merging this into master

so what I need for you to do is switch to the erik branch by doing the following (make sure you have no uncommitted changes first in your local branch first*)
git fetch
git checkout erik
This will first grab the remote erik branch onto your computer, then create a local branch linked to the remote branch and switch to it.
Then you should open the project in Unity and see the play button. If everything is working correctly, you should see a long-legged tree of life doing an idle animation. Pressing Right arrow should move right, left arrow should move left and pressing enter should trigger an attack animation. 

If that is working correctly I would like you then review the Tree of Life game object I created and the attached script to see if there's any better way to do any of the things I accomplished. Please put your feedback on this issue. Be sure to switch back to your own branch before resuming development on your features.

*You can do this with a git commit, but if you don't want to you can instead use "git stash save" which will store your changes elsewhere and revert the pending changes in your local branch, after switching back to your own branch do "git stash pop" to restore them.

**Comment by b0npls** [comment]
Alright, so as far as I can tell everything is working as you have described it. I'm not sure if the animation is coming through 100% clearly, and I only say that basically there are some grey "triangles" in the back of it, but that could just be its 4th leg (back left? I think). The motion is smooth and the attack works. That all being said, I am SUPER impressed with this things sprite, animations, and smoothness. Super awesome.

Here's my improvements/thoughts:
Organization:
The animations should be in their own animations folder within a folder titled "Animations". This is purely for organizational purposes but will make all the different later. Especially if we name multiple things "attack" or "walkforward". So the Animations folder will be under assets like all the other folders. Then in it there should be a folder called "tree of life". We should put the Animation Controller and the individual animations in there. We will NOT reuse those animations for others as they are specifically tied to the sprites involved. We can copy them and make edits later if we want the same type thing later.

I'm not sure what this other Animation controller is "out_8"? Was that just a trial run?

It's best practice to name Animation Controllers with an _ at the front of them. It puts them first in their folders and its easy to read. 

You should have two different sprite sheets for the walking and attacking animations. This is just organizational, but it makes finding things a lot easier.

Speaking of organization, your TreeOfLife object is functional, but not future proof. I recommend making a childed object of your tree to hold the Sprite Renderer component. This child object only needs to be for the sprite, and then allows you to mess around with the size of the sprite (scaling) without affecting the size of colliders and the like. It may not be needed for your TreeOfLife at this time, but it is a best practice type of thing. It will require you to go one level deeper when creating your animations, but it shouldn't be too big of a issue only one level down (further nested children becomes a huge problem with animations in the sense that it takes time just to click your way through the nest, but I'll mention that when it comes up). You should always keep your Animator on the highest level above all the things you're actually animating so that it governs all the children (so in other words it's good where it is at). 

I noticed your TreeOfLife looks a bit grainy. I didn't mess around with the sprite sheet too much to see if that's just how it is, but I can mention you can change the clarity of your sprites if you look at the sprite sheet itself in the inspector. There you will find a setting called "Filter Mode". By default I think it's always on "bilinear", but you can change that to either "Trilinear" or "Point (no filter)". I have mostly used Point for all my pixel art as it comes through exactly how it was in gimp/paint. I don't think it makes too much of a difference for your sprite, but you can check it out.

Whenever a new script is created, it is automatically created in assets if not specified where it needs to go (IE: right clicking in a folder to create the script. Usually when you just add a new script component it will add up in the top assets folder). You should put all scripts into the script folder. I don't know if you want to do that before I merge my branch with the master yet, but I don't know if it makes a difference.

I really appreciate you called your Animator "anim" cause that's what I call mine :]

In regards to your code, you are using "update". I don't think it matters too much for your movement as that is done via moving the transform directly (which means no physics is involved, which further means in this situation that at all times it has a velocity of 0), however I would recommend using FixedUpdate as the function of choice for anything that involves physics. We haven't worked out how we are going to do attacks and damage yet, and it can all be done with or without physics I'm sure, but I have had lots of issues with things in the past not being in the correct Update/FixedUpdate method. FixedUpdate is specifically called anytime physics is being calculated, which can be faster or slower than Update depending on the situation.

Also super minor right now, but I'm assuming you're going to move your code out of Update in the future into its own method to avoid cluttering Update up to much. I figure you did that for the proof of concept of this activity.

Along with that theme, we may want to make a separate attack script that can run all attacks for all characters, but that's more of a design decision to reduce size of code.

**Comment by b0npls** [comment]
So other things I noticed later on:

Animator:
Your animator is pretty chaotic looking. The flow is very nice, but you'll likely want to smooth out the attack animation into movements at some point. I'm not sure this is something that will be usable in the TreeOfLife as it currently exists, but there are things called Animation Layers that allow multiple animations to be happening on an object at the same time. This can be handy when you have an animation controlling the arms and legs suddenly switch to one where the legs stay the same but the arms switch. Now your animations are done via swapping through sprites quickly, so it might not be handy in this situation, but I thought I should mention it.

The more important thing to mention is Sorting Layers. In your Sprite Renderer component you'll notice it has a "Sorting Layer" and a "Order in Layer" as parts of the component. By default the Sorting Layer is... default, which just means that this is the complete bottom of all the layers. All other layers should appear in FRONT of things on this layer (IE: something with a different layer will always block the image of something on the Default layer, regardless of Order number). 

Now the way Unity sorts things on the SAME layer is through the the Order in Layer number. The lower the number, the more behind the image will be relative to other images. If something is on the SAME Sorting Layer with the SAME Order in Layer number, Unity will take a guess at which should be where. It is random and not advised (although many objects you can simply change the Z position of the object and it won't be weird cause of the orthogonal camera. This doesn't work with some ultra specific objects however, such as Particle Systems back in 4.6 (I think they got new options in 2017)). The reason I bring this up is because the second time I opened your branch, Unity was like "oh this TreeOfLife can just go behind this large banner" and I couldn't even see the GameObject. The lowest number the Order in Layer can go is 0, so I recommend usually starting things at a higher order than that in order to allow room to fall back. And I recommend having a PlayerStuff type of layer and a BackgroundStuff type of layer. We should save default for need only things.

I made Laser Defender II on ONLY the default layer. Which meant I had things from 0, to like 30 in the sorting layer iirc. That was pretty confusing and not a good system. That's also when I discovered Sorting Layers near the end of that project. GG EZ

**Comment by SimonSchama** [comment]
I have made most of these changes and merged them into master
